# Generated by Django 4.2.23 on 2025-08-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_force_password_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesubsection',
            name='video_file',
        ),
        migrations.AddField(
            model_name='coursesubsection',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
