# Generated by Django 4.2.23 on 2025-08-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_coursesubsection_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='attachments',
        ),
        migrations.AddField(
            model_name='course',
            name='attachment',
            field=models.URLField(blank=True, null=True),
        ),
    ]
