# Generated by Django 4.2.23 on 2025-08-08 11:15

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_course_attachments_course_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubsection',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube link (watch, youtu.be, shorts, or embed).', null=True, validators=[core.validators.validate_youtube_url]),
        ),
    ]
