# Generated by Django 4.2.23 on 2025-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_coursesubsection_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='turkish_name',
        ),
        migrations.AddField(
            model_name='course',
            name='dashboard_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_turkish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='main_page_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_turkish',
            field=models.BooleanField(default=False),
        ),
    ]
