# Generated by Django 4.2.23 on 2025-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_course_turkish_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesubsection',
            name='video_url',
        ),
        migrations.AddField(
            model_name='coursesubsection',
            name='bunny_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
