# Generated by Django 4.2.23 on 2025-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_coursesubsection_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubsection',
            name='bunny_video_id',
            field=models.URLField(blank=True, help_text='Paste Bunny Direct Play URL (playlist.m3u8 or .mp4) OR just the video ID', null=True),
        ),
    ]
