# Generated by Django 4.2.23 on 2025-08-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_coursesubsection_bunny_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='course_attachments/'),
        ),
    ]
