# Generated by Django 4.2.23 on 2025-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_course_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursesubsection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
