# Generated by Django 4.2.23 on 2025-09-22 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_coursesection_order_coursesubsection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('video', 'Video'), ('test', 'Test')], db_index=True, default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='allowed_tests',
            field=models.ManyToManyField(blank=True, limit_choices_to={'course_type': 'test'}, related_name='users_with_test_access', to='core.course'),
        ),
    ]
