# Generated by Django 4.2.23 on 2025-09-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_test_models'),
        ('core', '0012_add_test_models'),
    ]

    operations = [
    ]
