# Generated by Django 4.2.23 on 2025-10-26 11:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_course_course_type_customuser_allowed_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='digital_products/images/')),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. 3h 56m', max_length=32)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('uploader_name', models.CharField(default='ITAuditLab', max_length=120)),
                ('static_avatar', models.ImageField(blank=True, null=True, upload_to='digital_products/avatars/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Boşsa price * 4 olarak otomatik ayarlanır.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='USD', max_length=3)),
                ('ruul_pay_link', models.URLField(blank=True)),
                ('license_password', models.CharField(help_text='PDF şifresi (Ruul gösterir)', max_length=64)),
                ('source_pdf', models.FileField(blank=True, null=True, upload_to='digital_products/source_pdf/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_intents', to='core.digitalproduct')),
            ],
        ),
    ]
