# Generated by Django 4.2.23 on 2026-10-06 05:45

from django.conf import settings
from django.db import migrations, models
from core.migration_operations import EnsureCreateModel
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_set_cism_course_descriptions"),
    ]

    operations = [
        EnsureCreateModel(
            name="Bootcamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField()),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("level", models.CharField(blank=True, max_length=100)),
                (
                    "price",
                    models.PositiveIntegerField(help_text="TL olarak yaz. Örn: 10000"),
                ),
                ("currency", models.CharField(default="TRY", max_length=10)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="bootcamps/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        EnsureCreateModel(
            name="NewsletterLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "source",
                    models.CharField(
                        default="cybersecurity_fit_test_popup", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="digitalproduct",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Beginner", "🌱 Temel"),
                    ("Intermediate", "📚 Orta"),
                    ("Advanced", "🔥 Zor"),
                ],
                default="Beginner",
                max_length=20,
            ),
        ),
        EnsureCreateModel(
            name="PageVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        EnsureCreateModel(
            name="BootcampInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bootcamp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.bootcamp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
