# Generated by Django 4.2.23 on 2026-10-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_bootcamp_newsletterlead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_mobile',
            field=models.BooleanField(db_index=True, default=False, help_text='Bu hesabın mobil uygulamaya giriş yapmasına izin verir.', verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_last_date',
            field=models.DateField(blank=True, help_text='Mobil erişimin son günü (Türkiye saati). Boşsa sınırsız erişim.', null=True, verbose_name='Last date'),
        ),
    ]
