# Generated by Django 4.2.23 on 2026-10-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_customuser_is_mobile_customuser_mobile_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_full_access',
            field=models.BooleanField(db_index=True, default=False, help_text='Bütün öğrenme yollarını açar. Kapalı hesap yalnızca ücretsiz yolu görür.', verbose_name='Mobil tam erişim'),
        ),
    ]
