# Generated by Django 4.2.23 on 2026-10-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customuser_mobile_full_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_paid_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ücretli mobil erişim bitişi'),
        ),
    ]
