# Generated by Django 4.2.23 on 2026-10-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_customuser_mobile_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_must_change_password',
            field=models.BooleanField(default=False, verbose_name='İlk girişte şifre yenileme'),
        ),
    ]
