# Generated by Django 4.2.23 on 2026-10-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_customuser_mobile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_email_verified',
            field=models.BooleanField(default=True, help_text='Mevcut/yönetici tarafından tanımlanan hesaplar doğrulanmış kabul edilir. Yeni mobil kayıtlar e-posta onayı gerektirir.', verbose_name='Mobil e-posta doğrulandı'),
        ),
    ]
