# Generated by Django 4.2.30 on 2026-08-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=60, unique=True, verbose_name='Sertifika ID')),
                ('participant_name', models.CharField(max_length=120, verbose_name='Katılımcı')),
                ('issue_date', models.DateField(verbose_name='Veriliş tarihi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Son geçerlilik')),
                ('status', models.CharField(choices=[('valid', 'Geçerli'), ('expired', 'Süresi dolmuş'), ('revoked', 'İptal')], default='valid', max_length=12, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
            },
        ),
        migrations.CreateModel(
            name='JobMarketCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60, unique=True, verbose_name='Ülke')),
                ('flag', models.CharField(blank=True, max_length=8, verbose_name='Bayrak')),
                ('grc', models.PositiveIntegerField(default=0)),
                ('it_audit', models.PositiveIntegerField(default=0, verbose_name='IT Audit')),
                ('it_risk', models.PositiveIntegerField(default=0, verbose_name='IT Risk')),
                ('it_controls', models.PositiveIntegerField(default=0, verbose_name='IT Controls')),
                ('compliance', models.PositiveIntegerField(default=0)),
                ('cyber_risk', models.PositiveIntegerField(default=0, verbose_name='Cyber Risk')),
                ('is_demo', models.BooleanField(default=True, verbose_name='Demo veri')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
            ],
            options={
                'verbose_name': 'İş piyasası verisi',
                'verbose_name_plural': 'İş piyasası verileri',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('profile_type', models.CharField(choices=[('student', 'Üniversite öğrencisi'), ('graduate', 'Yeni mezun'), ('working', 'Çalışıyor')], max_length=20, verbose_name='Profil')),
                ('english_awareness', models.BooleanField(default=False, verbose_name='İngilizce farkındalığı')),
                ('weekly_time', models.BooleanField(default=False, verbose_name='Haftalık zaman ayırabilir')),
                ('age_over_45', models.BooleanField(default=False, verbose_name='45 yaş üzeri')),
                ('existing_it_experience', models.BooleanField(default=False, verbose_name='İlgili tecrübe')),
                ('test_score', models.PositiveSmallIntegerField(default=0, verbose_name='Test puanı')),
                ('result_type', models.CharField(choices=[('strong', 'Güçlü Uyum'), ('develop', 'Uygun — Bazı Alanları Güçlendir'), ('wait', 'Şimdilik Bekle')], max_length=20, verbose_name='Sonuç')),
                ('student_discount_eligible', models.BooleanField(default=False, verbose_name='Öğrenci avantajı')),
                ('consent', models.BooleanField(default=False, verbose_name='İletişim izni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leadler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bootcamp_price', models.PositiveIntegerField(default=59999, verbose_name='Bootcamp fiyatı')),
                ('payment_url', models.URLField(blank=True, verbose_name='Ödeme URL')),
                ('program_start_date', models.CharField(default='Yakında', max_length=80, verbose_name='Program başlangıcı')),
                ('seats_remaining', models.PositiveSmallIntegerField(default=12, verbose_name='Kalan kontenjan')),
                ('student_discount', models.PositiveSmallIntegerField(default=50, verbose_name='Öğrenci indirimi (%)')),
                ('potential_customer_count', models.PositiveIntegerField(default=490000, verbose_name='Potansiyel kurum')),
                ('certificate_validity', models.CharField(default='Admin tarafından belirlenir', max_length=100, verbose_name='Sertifika geçerliliği')),
                ('minimum_coe', models.CharField(default='30 COE', max_length=40, verbose_name='Minimum eğitim kredisi')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Ücretsiz ders URL')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp URL')),
                ('contact_email', models.EmailField(default='merhaba@grcustasi.com', max_length=254, verbose_name='İletişim e-postası')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site ayarı',
                'verbose_name_plural': 'Site ayarları',
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('consent', models.BooleanField(default=False, verbose_name='İletişim izni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Bekleme listesi kaydı',
                'verbose_name_plural': 'Bekleme listesi',
                'ordering': ['-created_at'],
            },
        ),
    ]
