# Generated by Django 4.2.30 on 2026-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_sitesetting_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmarketcount',
            options={'ordering': ['id'], 'verbose_name': 'İş piyasası verisi', 'verbose_name_plural': 'İş piyasası verileri'},
        ),
        migrations.AddField(
            model_name='jobmarketcount',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son kontrol'),
        ),
        migrations.AddField(
            model_name='jobmarketcount',
            name='last_error',
            field=models.CharField(blank=True, max_length=240, verbose_name='Son hata'),
        ),
        migrations.AddField(
            model_name='jobmarketcount',
            name='search_url',
            field=models.URLField(blank=True, verbose_name='Arama bağlantısı'),
        ),
        migrations.AddField(
            model_name='jobmarketcount',
            name='source_label',
            field=models.CharField(default='Manuel veri', max_length=80, verbose_name='Veri kaynağı'),
        ),
    ]
