# Generated by Django 4.2.27 on 2026-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_jobmarketcount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='region',
            field=models.CharField(blank=True, choices=[('europe', 'Avrupa'), ('usa', 'ABD / Kuzey Amerika'), ('south_america', 'Güney Amerika'), ('asia', 'Asya'), ('australia', 'Avustralya / Okyanusya')], max_length=20, verbose_name='Yurtdışı bölgesi'),
        ),
        migrations.AddField(
            model_name='lead',
            name='residence_type',
            field=models.CharField(blank=True, choices=[('turkey', 'Türkiye'), ('abroad', 'Yurtdışı')], max_length=12, verbose_name='Yaşanılan yer'),
        ),
    ]
