# Generated by Django 4.2.27 on 2026-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_lead_region_lead_residence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='career_clarity',
            field=models.BooleanField(default=False, verbose_name='Kariyer hedefi net'),
        ),
        migrations.AddField(
            model_name='lead',
            name='effort_awareness',
            field=models.BooleanField(default=False, verbose_name='Çalışma yoğunluğu farkındalığı'),
        ),
        migrations.AddField(
            model_name='lead',
            name='eligibility_awareness',
            field=models.BooleanField(default=False, verbose_name='Rol uygunluğu farkındalığı'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ethics_commitment',
            field=models.BooleanField(default=False, verbose_name='Etik kullanım taahhüdü'),
        ),
        migrations.AddField(
            model_name='lead',
            name='opportunity_awareness',
            field=models.BooleanField(default=False, verbose_name='İş fırsatları farkındalığı'),
        ),
    ]
