# Generated by Django 4.2.23 on 2026-08-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_update_grc_ustasi_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('consent', models.BooleanField(default=True, verbose_name='Bülten izni')),
                ('discount_percent', models.PositiveSmallIntegerField(default=5, verbose_name='İndirim oranı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt tarihi')),
            ],
            options={
                'verbose_name': 'Bülten abonesi',
                'verbose_name_plural': 'Bülten aboneleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
