# Generated by Django 4.2.23 on 2026-10-04 03:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_update_bootcamp_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_session_id', models.CharField(max_length=255, unique=True)),
                ('payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('paid_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('product', models.CharField(default='Travel Bootcamp', editable=False, max_length=80)),
                ('registered_at', models.DateTimeField()),
                ('starts_on', models.DateField()),
                ('payment_status', models.CharField(default='paid', editable=False, max_length=10)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='travelregistration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='travel_email_case_insensitive'),
        ),
        migrations.AddField(
            model_name='travelpayment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='landing.travelregistration'),
        ),
    ]
