# Generated by Django 4.2.23 on 2026-10-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_travelpayment_travelregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt tarihi')),
            ],
            options={
                'verbose_name': 'Mobil uygulama bekleme kaydı',
                'verbose_name_plural': 'Mobil uygulama bekleme listesi',
                'ordering': ('-created_at',),
            },
        ),
    ]
