# Generated by Django 4.2.23 on 2026-08-23 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('notification_type', models.CharField(max_length=40)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SkoolInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Ad soyad')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=160)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('invited', 'Davet edildi'), ('claimed', 'Kullanıldı'), ('revoked', 'İptal edildi')], db_index=True, default='invited', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Skool daveti',
                'verbose_name_plural': 'Skool davetleri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SkoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('meeting_duration_minutes', models.PositiveSmallIntegerField(default=90)),
                ('daily_slot_count', models.PositiveSmallIntegerField(default=3)),
                ('minimum_gap_minutes', models.PositiveSmallIntegerField(default=15)),
                ('display_timezone', models.CharField(default='Europe/Istanbul', max_length=64)),
                ('meet_url', models.URLField(default='https://meet.google.com/jbv-csdm-eyy')),
            ],
            options={
                'verbose_name': 'Skool ayarı',
                'verbose_name_plural': 'Skool ayarları',
            },
        ),
        migrations.CreateModel(
            name='TravelAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('local_available_start', models.TimeField()),
                ('local_available_end', models.TimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seyahat ve uygunluk',
                'verbose_name_plural': 'Seyahat ve uygunluk',
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='SkoolUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('state', models.CharField(choices=[('IDENTITY_VERIFIED', 'Kimlik doğrulandı'), ('TEST_IN_PROGRESS', 'Test sürüyor'), ('TEST_COMPLETED', 'Test tamamlandı'), ('AUDIO_IN_PROGRESS', 'Ses kaydı dinleniyor'), ('AUDIO_COMPLETED', 'Ses kaydı tamamlandı'), ('READY_TO_BOOK', 'Rezervasyona hazır'), ('BOOKED', 'Görüşme planlandı'), ('COMPLETED', 'Tamamlandı')], db_index=True, default='IDENTITY_VERIFIED', max_length=24)),
                ('current_question', models.PositiveSmallIntegerField(default=1)),
                ('intro_seen', models.BooleanField(default=False)),
                ('identity_verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_started_at', models.DateTimeField(blank=True, null=True)),
                ('test_completed_at', models.DateTimeField(blank=True, null=True)),
                ('audio_started_at', models.DateTimeField(blank=True, null=True)),
                ('audio_completed_at', models.DateTimeField(blank=True, null=True)),
                ('audio_listened_seconds', models.PositiveIntegerField(default=0)),
                ('audio_last_position', models.PositiveIntegerField(default=0)),
                ('audio_duration_seconds', models.PositiveIntegerField(default=0)),
                ('audio_progress_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='skool.skoolinvitation')),
            ],
            options={
                'verbose_name': 'Skool kullanıcısı',
                'verbose_name_plural': 'Skool kullanıcıları',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OnboardingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='skool.skooluser')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date', models.DateField(db_index=True)),
                ('start_at_utc', models.DateTimeField(unique=True)),
                ('end_at_utc', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Müsait'), ('booked', 'Dolu'), ('disabled', 'Kapalı')], db_index=True, default='available', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='skool.travelavailability')),
            ],
            options={
                'ordering': ('start_at_utc',),
            },
        ),
        migrations.CreateModel(
            name='MeetingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('rescheduled', 'Değiştirildi'), ('cancelled', 'İptal')], db_index=True, default='active', max_length=16)),
                ('meeting_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='skool.meetingslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='skool.skooluser')),
            ],
        ),
        migrations.CreateModel(
            name='CareerTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveSmallIntegerField()),
                ('question_text', models.TextField()),
                ('selected_option', models.CharField(max_length=240)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='skool.skooluser')),
            ],
            options={
                'ordering': ('question_id',),
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='skool.meetingbooking')),
                ('new_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_booking_history', to='skool.meetingslot')),
                ('old_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_booking_history', to='skool.meetingslot')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('availability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='skool.travelavailability')),
            ],
        ),
        migrations.AddConstraint(
            model_name='meetingslot',
            constraint=models.UniqueConstraint(fields=('availability', 'local_date', 'start_at_utc'), name='unique_skool_slot'),
        ),
        migrations.AddConstraint(
            model_name='meetingbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='one_active_skool_booking'),
        ),
        migrations.AddConstraint(
            model_name='careertestanswer',
            constraint=models.UniqueConstraint(fields=('user', 'question_id'), name='unique_skool_answer'),
        ),
    ]
