# Generated by Django 4.2.23 on 2026-08-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0002_skooluser_foundation_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingbooking',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı'), ('rescheduled', 'Değiştirildi'), ('cancelled', 'İptal')], db_index=True, default='active', max_length=16),
        ),
    ]
