# Generated by Django 4.2.23 on 2026-10-01 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0009_skooluser_withdrawal_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingslot',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='skool.travelavailability'),
        ),
    ]
