# Generated by Django 4.2.23 on 2026-10-06 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mobile_api.storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("file", models.FileField(upload_to="mobile/audio/")),
                (
                    "name_key",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="shield", max_length=32)),
                ("color", models.CharField(default="#166B5B", max_length=7)),
                ("difficulty", models.CharField(default="beginner", max_length=16)),
                ("minutes", models.PositiveIntegerField(default=10)),
                ("premium", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LearningSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("questions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobile_api.learningpath",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="mobile_api.learningpath",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("choice", "choice"),
                            ("multi_select", "multi_select"),
                            ("fill_blank", "fill_blank"),
                            ("text", "text"),
                            ("image", "image"),
                            ("audio", "audio"),
                            ("scenario", "scenario"),
                            ("voice", "voice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("context", models.TextField(blank=True)),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=list, help_text='[{"id":"a","text":"..."}]'
                    ),
                ),
                (
                    "answer",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Doğru seçenek ID listesi veya kabul edilen metinler",
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("hint", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="mobile/images/")),
                ("difficulty", models.CharField(default="beginner", max_length=16)),
                ("base_xp", models.PositiveIntegerField(default=10)),
                ("premium", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mobile_api.audioasset",
                    ),
                ),
                (
                    "intro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="mobile_api.audioasset",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mobile_api.module",
                    ),
                ),
                (
                    "paths",
                    models.ManyToManyField(
                        blank=True,
                        related_name="questions",
                        to="mobile_api.learningpath",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.JSONField()),
                ("is_correct", models.BooleanField()),
                ("xp_change", models.IntegerField(default=0)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile_api.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mobile_api.learningsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="XPTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("reason", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile_api.questionattempt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=mobile_api.storage.PrivateVoiceStorage(),
                        upload_to="recordings/",
                    ),
                ),
                ("duration", models.PositiveIntegerField()),
                (
                    "review_status",
                    models.CharField(
                        choices=[("pending", "pending"), ("reviewed", "reviewed")],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobile_api.questionattempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPathProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "completed",
                    models.ManyToManyField(blank=True, to="mobile_api.question"),
                ),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobile_api.learningpath",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                (
                    "product_id",
                    models.CharField(
                        default="grcustasi_premium_monthly", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "trial"),
                            ("active", "active"),
                            ("expired", "expired"),
                            ("cancelled", "cancelled"),
                            ("grace_period", "grace_period"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="userpathprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "path"), name="mobile_user_path_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionattempt",
            constraint=models.UniqueConstraint(
                fields=("session", "question"), name="mobile_session_question_unique"
            ),
        ),
    ]
