# Generated by Django 4.2.23 on 2026-10-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile_api", "0004_billingidentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="goals",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Hedef adları: Sertifika, Denetim, Teknik bilgi vb.",
            ),
        ),
    ]
