# Generated by Django 4.2.23 on 2026-10-06 05:16

from django.db import migrations, models
import mobile_api.storage


class Migration(migrations.Migration):

    dependencies = [
        ("mobile_api", "0005_question_goals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audioasset",
            name="file",
            field=models.FileField(
                storage=mobile_api.storage.PrivateVoiceStorage(), upload_to="audio/"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=mobile_api.storage.PrivateVoiceStorage(),
                upload_to="images/",
            ),
        ),
    ]
