# Generated by Django 4.2.23 on 2026-10-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0008_demo_mobile_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.JSONField(blank=True, default=list, help_text="Doğru seçenek ID listesi veya kabul edilen metinler. sentence_order için ID'leri doğru cümle sırasıyla yazın; şıklardaki correct işaretleri bu türde kullanılmaz."),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('choice', 'choice'), ('multi_select', 'multi_select'), ('fill_blank', 'fill_blank'), ('text', 'text'), ('image', 'image'), ('audio', 'audio'), ('scenario', 'scenario'), ('voice', 'voice'), ('sentence_order', 'sentence_order'), ('drag_select', 'drag_select')], max_length=20),
        ),
    ]
