# Generated by Django 4.2.23 on 2026-10-06 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0010_risk_workshop_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True, verbose_name='Seviye')),
                ('title', models.CharField(max_length=180, verbose_name='Hediye / rozet adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('kind', models.CharField(choices=[('badge', 'Dijital rozet'), ('gift', 'Yönetici tarafından teslim edilen hediye')], default='badge', max_length=12, verbose_name='Tür')),
                ('published', models.BooleanField(default=False, verbose_name='Profilde göster')),
            ],
            options={
                'verbose_name': 'Mobil seviye hediyesi',
                'verbose_name_plural': 'Mobil seviye hediyeleri',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='LevelSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('xp_per_level', models.PositiveIntegerField(default=100, help_text='Seviye 0’dan başlar. Örneğin 100 ise 100 XP = seviye 1.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Seviye başına XP')),
            ],
            options={
                'verbose_name': 'Mobil seviye ayarı',
                'verbose_name_plural': 'Mobil seviye ayarları',
            },
        ),
    ]
