# Generated by Django 4.2.23 on 2026-10-06 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile_api', '0011_levelreward_levelsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevelReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Kazanılma tarihi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Hediye teslim tarihi')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_api.levelreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobil kazanılan hediye',
                'verbose_name_plural': 'Mobil kazanılan hediyeler',
            },
        ),
        migrations.AddConstraint(
            model_name='userlevelreward',
            constraint=models.UniqueConstraint(fields=('user', 'reward'), name='mobile_user_level_reward_unique'),
        ),
    ]
