# Generated by Django 4.2.23 on 2026-10-06 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0014_all_question_types_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='card_pages',
            field=models.JSONField(blank=True, default=list, help_text='info türünde: [{"title":"Başlık","body":"**Kalın**, *italik* metin","reveal":"Dokununca açılan açıklama"}]. Her sayfa kaydırılarak geçilir.', verbose_name='Bilgi kartı sayfaları'),
        ),
        migrations.AddField(
            model_name='voicesubmission',
            name='feedback_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-posta gönderildi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('info', 'info'), ('choice', 'choice'), ('multi_select', 'multi_select'), ('fill_blank', 'fill_blank'), ('text', 'text'), ('image', 'image'), ('audio', 'audio'), ('scenario', 'scenario'), ('voice', 'voice'), ('sentence_order', 'sentence_order'), ('drag_select', 'drag_select')], max_length=20),
        ),
        migrations.CreateModel(
            name='MobileSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('free_path', models.ForeignKey(blank=True, help_text='Ücretsiz hesaplara yalnızca bu yayınlanmış, ortak yol gösterilir. Soruların eski premium işaretleri erişimi etkilemez.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_api.learningpath', verbose_name='Ücretsiz öğrenme yolu')),
            ],
            options={
                'verbose_name': 'Mobil uygulama ayarları',
                'verbose_name_plural': 'Mobil uygulama ayarları',
            },
        ),
    ]
