# Generated by Django 4.2.23 on 2026-10-06 08:05

from django.db import migrations, models
import mobile_api.contacts


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0016_access_and_information_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesettings',
            name='whatsapp_phone',
            field=models.CharField(blank=True, default='0032 476 073 171', help_text='Ülke koduyla yazın (+32 veya 0032). Boş bırakılırsa iletişim düğmesi gizlenir.', max_length=32, validators=[mobile_api.contacts.validate_whatsapp_number], verbose_name='Volkan WhatsApp numarası'),
        ),
    ]
