# Generated by Django 4.2.23 on 2026-10-06 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile_api', '0017_mobilesettings_whatsapp_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_session_id', models.CharField(max_length=255, unique=True)),
                ('payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('paid_at', models.DateTimeField()),
                ('access_until', models.DateTimeField()),
                ('amount_minor', models.PositiveIntegerField(default=209900)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobil uygulama ödemesi',
                'verbose_name_plural': 'Mobil uygulama ödemeleri',
            },
        ),
    ]
