# Generated by Django 4.2.23 on 2026-10-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0018_mobilepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
