# Generated by Django 4.2.23 on 2026-10-06 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0019_learningsession_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAdminAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_error', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Mobil Telegram bildirimi',
                'verbose_name_plural': 'Mobil Telegram bildirimleri',
            },
        ),
        migrations.CreateModel(
            name='MotivationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='GRC Ustası • Bugünün adımı', max_length=80, verbose_name='Başlık')),
                ('body', models.CharField(max_length=240, verbose_name='Motivasyon mesajı')),
                ('published', models.BooleanField(default=True, verbose_name='Yayınlandı')),
                ('day', models.DateField(blank=True, help_text='Boşsa günlük mesajlar arasında dönüşümlü kullanılır. Doluysa yalnızca bu gün gönderilir.', null=True, unique=True, verbose_name='Özel gün')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Mobil motivasyon mesajı',
                'verbose_name_plural': 'Mobil motivasyon mesajları',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='mobilesettings',
            name='notification_hour',
            field=models.PositiveSmallIntegerField(default=19, validators=[django.core.validators.MaxValueValidator(23)], verbose_name='Bildirim saati (telefonun yerel saati)'),
        ),
        migrations.AddField(
            model_name='mobilesettings',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Günlük motivasyon bildirimleri'),
        ),
    ]
