# Generated by Django 4.2.23 on 2026-10-06 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile_api', '0021_seed_motivation_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilepayment',
            name='receipt_error',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='mobilepayment',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödeme e-postası gönderildi'),
        ),
        migrations.CreateModel(
            name='MobileCheckoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
