# Generated by Django 4.2.23 on 2026-10-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile_api', '0022_mobilepayment_receipt_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('erased_at', models.DateTimeField(blank=True, null=True)),
                ('pending_files', models.JSONField(blank=True, default=list)),
                ('email_to_notify', models.EmailField(blank=True, max_length=254)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobil hesap silme talebi',
                'verbose_name_plural': 'Mobil hesap silme talepleri',
            },
        ),
    ]
