# Generated by Django 4.2.23 on 2026-10-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0023_accountdeletionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_transaction_id', models.CharField(max_length=100)),
                ('signed_at', models.DateTimeField()),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobile_api.subscription')),
            ],
        ),
    ]
