# Generated by Django 4.2.23 on 2026-10-09 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0024_appleentitlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Başlık')),
                ('situation', models.TextField(verbose_name='Vaka / senaryo')),
                ('sentence', models.JSONField(help_text='Doğru sırayla yazın: ["Neden nedeniyle", "olay gerçekleşebilir", "ve sonuç oluşabilir."]', verbose_name='Doğru risk cümlesinin parçaları')),
                ('controls', models.JSONField(help_text='["Birinci seçenek", "İkinci seçenek", "Üçüncü seçenek"]', verbose_name='Kontrol seçenekleri')),
                ('control', models.PositiveSmallIntegerField(help_text='İlk seçenek 1, ikinci 2, üçüncü 3.', verbose_name='Doğru kontrolün sıra numarası')),
                ('control_reason', models.TextField(verbose_name='Kontrol açıklaması')),
                ('evidence', models.JSONField(help_text='["Birinci kanıt", "İkinci kanıt", "Üçüncü kanıt"]', verbose_name='Kanıt seçenekleri')),
                ('proof', models.PositiveSmallIntegerField(help_text='İlk seçenek 1, ikinci 2, üçüncü 3.', verbose_name='Doğru kanıtın sıra numarası')),
                ('evidence_reason', models.TextField(verbose_name='Kanıt açıklaması')),
                ('likelihood', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Örnek olasılık')),
                ('impact', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Örnek etki')),
                ('published', models.BooleanField(default=False, help_text='Giriş yapmadan herkese gösterilir. Yanıtlar cihazda değerlendirilir; özel/ücretli içerik eklemeyin.', verbose_name='Atölyede göster')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Gösterim sırası')),
            ],
            options={
                'verbose_name': 'Vaka atölyesi sorusu',
                'verbose_name_plural': 'Vaka atölyesi soruları',
                'ordering': ['order', 'id'],
            },
        ),
    ]
