# Generated by Django 4.2.23 on 2026-10-09 16:33

from django.db import migrations, models
import django.db.models.deletion
import mobile_api.storage
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0026_seed_practice_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='in_workshop',
            field=models.BooleanField(default=False, help_text='Yayınlanmış soru giriş yapmadan herkese açılır; yanıt anahtarı cihazda değerlendirme için indirilir. Özel/ücretli içerik seçmeyin.', verbose_name='Giriş öncesi vaka atölyesinde göster'),
        ),
        migrations.CreateModel(
            name='WorkshopVoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Geri bildirim e-postası')),
                ('file', models.FileField(storage=mobile_api.storage.PrivateVoiceStorage(), upload_to='workshop_voice/')),
                ('duration', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField(blank=True, verbose_name='Geri bildirim')),
                ('feedback_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_api.question')),
            ],
            options={
                'verbose_name': 'Atölye sesli yanıtı',
                'verbose_name_plural': 'Atölye sesli yanıtları',
            },
        ),
    ]
