# Generated by Django 5.2.17 on 2026-09-20 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('is_demo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('evidence_guidance', models.TextField()),
                ('framework', models.CharField(max_length=60)),
                ('theme', models.CharField(max_length=80)),
                ('risk', models.CharField(choices=[('high', 'Yüksek'), ('medium', 'Orta'), ('low', 'Düşük')], max_length=10)),
                ('intern_visible', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='workspace.audit')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(choices=[('compliant', 'Uygun'), ('partial', 'Kısmen uygun'), ('noncompliant', 'Uygun değil'), ('pending', 'İnceleme bekliyor')], max_length=20)),
                ('rationale', models.TextField()),
                ('private_note', models.TextField(blank=True)),
                ('customer_visible', models.BooleanField(default=True)),
                ('control', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation', to='workspace.control')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('recommendation', models.TextField()),
                ('severity', models.CharField(choices=[('high', 'Yüksek'), ('medium', 'Orta')], max_length=10)),
                ('customer_visible', models.BooleanField(default=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='workspace.audit')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('executive', 'Kurum yöneticisi'), ('it', 'BT sorumlusu'), ('auditor', 'Denetçi'), ('intern', 'Stajyer')], max_length=20)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.audit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.organization'),
        ),
        migrations.CreateModel(
            name='ResponseRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('implemented', 'Yapılıyor'), ('partial', 'Kısmen yapılıyor'), ('missing', 'Yapılmıyor'), ('na', 'Uygulanamaz'), ('unanswered', 'Cevaplanmadı')], max_length=20)),
                ('explanation', models.TextField()),
                ('declaration', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='workspace.control')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(fields=('audit', 'code'), name='unique_audit_control_code'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'audit'), name='one_membership_per_audit'),
        ),
    ]
