# Generated by Django 5.2.17 on 2026-09-20 04:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='appointment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='appointment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='appointment_status',
            field=models.CharField(choices=[('none', 'Planlanmadı'), ('proposed', 'BT onayı bekleniyor'), ('counter', 'Denetim ekibi onayı bekleniyor'), ('confirmed', 'Onaylandı')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='phase',
            field=models.CharField(choices=[('responses', 'BT yanıtları'), ('fieldwork', 'Saha denetimi'), ('remediation', 'Bulgu giderme'), ('completed', 'Tamamlandı')], default='responses', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='control',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finding', to='workspace.control'),
        ),
        migrations.AddField(
            model_name='finding',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('open', 'Açık'), ('remediation_submitted', 'Giderim incelemede'), ('disputed', 'İtiraz incelemede'), ('closed', 'Kapatıldı')], default='open', max_length=25),
        ),
        migrations.AddField(
            model_name='finding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='responserevision',
            name='status',
            field=models.CharField(choices=[('implemented', 'Yapılıyor'), ('partial', 'Kısmen yapılıyor'), ('missing', 'Yapılmıyor'), ('na', 'Uygulanamaz'), ('unanswered', 'Başlanmadı')], max_length=20),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=80)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.audit')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FindingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('remediate', 'Giderim bildirimi'), ('dispute', 'İtiraz'), ('close', 'Kapanış onayı'), ('reopen', 'Tekrar açıldı'), ('reject', 'İtiraz/giderim reddi')], max_length=30)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='workspace.finding')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('framework', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('test_steps', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'İnceleme bekliyor'), ('accepted', 'Kontrole dönüştürüldü'), ('rejected', 'Revizyon istendi')], default='pending', max_length=15)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='workspace.audit')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('control', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.control')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
