# Generated by Django 5.2.17 on 2026-09-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_audit_appointment_at_audit_appointment_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subdomain',
            field=models.SlugField(blank=True, help_text='Örnek: torbalibld. DNS/Render alan adı ayrıca yapılandırılmalıdır.', max_length=63, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='phase',
            field=models.CharField(choices=[('responses', 'BT yanıtları'), ('fieldwork', 'Saha denetimi'), ('remediation', 'Bulgu giderme'), ('completed', 'Sürekli kontrol')], default='responses', max_length=20),
        ),
    ]
