# Generated by Django 5.2.17 on 2026-09-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_evaluation_verified_finding_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Denetim şablonu',
                'verbose_name_plural': 'Denetim şablonları',
            },
        ),
        migrations.CreateModel(
            name='ControlDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('evidence_guidance', models.TextField(verbose_name='Beklenen kanıtlar / test rehberi')),
                ('framework', models.CharField(max_length=60)),
                ('theme', models.CharField(max_length=80)),
                ('risk', models.CharField(choices=[('high', 'Yüksek'), ('medium', 'Orta'), ('low', 'Düşük')], max_length=10)),
                ('intern_visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Kontrol kataloğu kaydı',
                'verbose_name_plural': 'Kontrol kataloğu',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='deficiency',
            field=models.CharField(blank=True, choices=[('design', 'Tasarım'), ('implementation', 'Uygulama'), ('both', 'Tasarım ve uygulama')], default='', max_length=20, verbose_name='Eksiklik türü'),
        ),
        migrations.AddField(
            model_name='membership',
            name='auditor_readonly',
            field=models.BooleanField(default=False, help_text='Stajyer bu denetimde tüm denetçi verilerini görebilir; hiçbir kayıt değiştiremez.', verbose_name='Stajyer denetçi görünümü (salt okunur)'),
        ),
        migrations.AddField(
            model_name='audit',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.audittemplate', verbose_name='Hazır denetim şablonu'),
        ),
        migrations.AddField(
            model_name='audittemplate',
            name='controls',
            field=models.ManyToManyField(blank=True, to='workspace.controldefinition', verbose_name='Hazır kontroller'),
        ),
        migrations.AddField(
            model_name='control',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_controls', to='workspace.controldefinition'),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(fields=('audit', 'source'), name='unique_audit_catalog_control'),
        ),
    ]
