# Generated by Django 5.2.17 on 2026-09-21 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_seed_audit_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80, verbose_name='Madde / fıkra')),
                ('text', models.TextField(verbose_name='Madde metni')),
            ],
            options={
                'verbose_name': 'Mevzuat maddesi',
                'verbose_name_plural': 'Mevzuat maddeleri',
                'ordering': ['legislation__code', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Kanun / düzenleme kodu')),
                ('title', models.CharField(max_length=250, verbose_name='Adı')),
                ('source_url', models.URLField(blank=True, verbose_name='Resmî kaynak')),
            ],
            options={
                'verbose_name': 'Kanun / düzenleme',
                'verbose_name_plural': 'Kanunlar / düzenlemeler',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='control',
            name='legal_articles',
            field=models.ManyToManyField(blank=True, related_name='audit_controls', to='workspace.legalarticle', verbose_name='Kanun / madde referansları'),
        ),
        migrations.AddField(
            model_name='controldefinition',
            name='legal_articles',
            field=models.ManyToManyField(blank=True, related_name='catalog_controls', to='workspace.legalarticle', verbose_name='Kanun / madde referansları'),
        ),
        migrations.AddField(
            model_name='legalarticle',
            name='legislation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='workspace.legislation', verbose_name='Kanun / düzenleme'),
        ),
        migrations.AddConstraint(
            model_name='legalarticle',
            constraint=models.UniqueConstraint(fields=('legislation', 'number'), name='unique_legal_article'),
        ),
    ]
