# Generated by Django 5.2.17 on 2026-09-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_privacy_accepted_at_user_privacy_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary_password',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
